### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by peufo** [peufo/benev#95]
- [ ] Système de compensation (création d'article, règles d'éligibilités)
  - [ ] Création d'article (nom, prix, mode de distribution, attribut/variante)
  - [ ] Règle d'attribution ? (Secteurs, horaires, heures)
  - [ ] Export des listes de distribution
- [ ] Logo et affiches de l'évènement
- [ ] Localisation des secteur et des périodes
